# Generated by Django 4.2.3 on 2023-07-22 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_successfulstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='successfulstudent',
            name='percentile',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='successfulstudent',
            name='university',
            field=models.CharField(choices=[('1', 'University of New South Wales'), ('2', 'Western Sydney University'), ('3', 'Griffith University'), ('4', 'University of New England'), ('5', 'Charles Stuart'), ('6', 'Australian National University'), ('7', 'University of Queensland')], max_length=1),
        ),
    ]
