# Generated by Django 4.1.5 on 2023-12-17 01:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_dynamiccontent_alter_successfulstudent_university'),
    ]

    operations = [
        migrations.CreateModel(
            name='entry_submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('atar', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99.95)])),
                ('gpa', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
            ],
            options={
                'verbose_name': 'Entry Submission',
                'verbose_name_plural': 'Entry Submissions',
            },
        ),
    ]
