# Generated by Django 4.1.5 on 2023-12-17 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_entry_submission'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='entry_submission',
            new_name='EntrySubmission',
        ),
    ]
