# Generated by Django 4.1.5 on 2023-12-17 04:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_rename_entry_submission_entrysubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrysubmission',
            name='atar',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
