# Generated by Django 4.1.5 on 2023-12-17 04:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_entrysubmission_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrysubmission',
            name='submitted_datetime',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
