# Generated by Django 5.0.2 on 2024-02-22 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_ucatcoursedetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ucatcoursedetails',
            options={'verbose_name': 'UCAT Course', 'verbose_name_plural': 'UCAT Course'},
        ),
        migrations.AddField(
            model_name='successfulstudent',
            name='testimonial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.testimonial'),
        ),
    ]
